// ===== TRANSLATIONS =====
const translations = {
  it: {
    logoSub: "Studio Commercialista",
    navHome: "Home",
    navServices: "Servizi",
    navAbout: "Chi Siamo",
    navTeam: "Team",
    navContact: "Contatti",
    heroTagline: "Professionalità · Affidabilità · Eccellenza",
    heroTitle: "Il Vostro Partner di Fiducia per la Consulenza Fiscale e Contabile",
    heroDesc: "Con oltre 20 anni di esperienza, offriamo soluzioni su misura per privati, professionisti e aziende in tutta Italia.",
    heroCta: "Contattaci Ora",
    heroServices: "I Nostri Servizi",
    stat1: "Anni di Esperienza",
    stat2: "Clienti Soddisfatti",
    stat3: "Professionisti",
    stat4: "Conformità Garantita",
    servicesLabel: "Cosa Facciamo",
    servicesTitle: "I Nostri Servizi",
    servicesDesc: "Offriamo una gamma completa di servizi contabili, fiscali e consulenziali per supportare la crescita del vostro business.",
    s1Title: "Consulenza Fiscale",
    s1Desc: "Pianificazione fiscale ottimizzata, dichiarazioni dei redditi, IVA, IMU e gestione di tutti gli adempimenti tributari.",
    s2Title: "Contabilità Aziendale",
    s2Desc: "Tenuta della contabilità ordinaria e semplificata, bilanci annuali, scritture contabili e reportistica gestionale.",
    s3Title: "Gestione Paghe",
    s3Desc: "Elaborazione cedolini, gestione INPS e INAIL, contratti di lavoro, assunzioni e cessazioni.",
    s4Title: "Costituzione Società",
    s4Desc: "Apertura di imprese individuali, SRL, SPA, e assistenza completa nelle pratiche di avvio attività.",
    s5Title: "Consulenza Strategica",
    s5Desc: "Business plan, analisi finanziaria, controllo di gestione e supporto nelle decisioni aziendali strategiche.",
    s6Title: "Contenzioso Tributario",
    s6Desc: "Assistenza in caso di accertamenti fiscali, ricorsi tributari, mediazioni con l'Agenzia delle Entrate.",
    serviceMore: "Scopri di più →",
    aboutLabel: "Chi Siamo",
    aboutTitle: "Un Riferimento nel Settore della Consulenza Commerciale in Italia",
    aboutP1: "Fondato nel 2004 a Milano, lo Studio MMJB è cresciuto fino a diventare uno dei più stimati studi commercialisti del Nord Italia. La nostra missione è fornire consulenza di alta qualità, personalizzata e aggiornata alle ultime normative.",
    aboutP2: "Serviamo clienti in tutta Italia e all'estero, con una particolare attenzione alle PMI, alle startup e agli imprenditori stranieri che desiderano operare nel mercato italiano.",
    abl1: "Iscritti all'Albo dei Dottori Commercialisti",
    abl2: "Aggiornamento continuo sulle normative fiscali",
    abl3: "Servizio multilingue (IT, FR, EN, AR)",
    abl4: "Software gestionali di ultima generazione",
    aboutCta: "Richiedi una Consulenza",
    badgeTxt: "Anni di Esperienza",
    teamLabel: "Le Persone",
    teamTitle: "Il Nostro Team",
    teamDesc: "Professionisti qualificati e appassionati al servizio dei vostri obiettivi.",
    role1: "Expert Comptable — Membre de ANCOT",
    bio1: "Specialista in fiscalità italiana e internazionale, contabilità aziendale, servizi CAF e Patronato. Accompagna privati, famiglie e imprese in tutte le pratiche amministrative e fiscali in Italia.",
    badgeCAF: "CAF Autorizzato",
    badgePatronato: "Patronato",
    patronatoLabel: "Patronato",
    patronatoTitle: "Servizi di Patronato",
    patronatoDesc: "Offriamo assistenza gratuita per tutte le pratiche previdenziali, assicurative e assistenziali presso INPS, INAIL e altri enti pubblici.",
    p1Title: "Pensione di Vecchiaia e Anticipata",
    p1Desc: "Domanda e calcolo della pensione di vecchiaia, anticipata, di anzianità e quota 100/103 presso INPS.",
    p2Title: "Invalidità Civile e Handicap",
    p2Desc: "Richiesta di riconoscimento dell'invalidità civile, cecità, sordità e legge 104 per persone con disabilità.",
    p3Title: "Indennità di Accompagnamento",
    p3Desc: "Domanda per l'indennità di accompagnamento per persone non autosufficienti che necessitano di assistenza continuativa.",
    p4Title: "NASpI / Disoccupazione",
    p4Desc: "Domanda di NASpI (indennità di disoccupazione), DIS-COLL per collaboratori e gestione delle prestazioni di disoccupazione.",
    p5Title: "Maternità e Congedi Parentali",
    p5Desc: "Domanda di indennità di maternità, paternità, congedo parentale e permessi ex legge 104 per lavoratori dipendenti e autonomi.",
    p6Title: "Infortuni sul Lavoro (INAIL)",
    p6Desc: "Denuncia e assistenza per infortuni sul lavoro e malattie professionali, rendita INAIL e riabilitazione.",
    p7Title: "Assegni Familiari",
    p7Desc: "Domanda di assegni familiari (ANF) per nuclei familiari con carichi di lavoro dipendente e pensionati.",
    p8Title: "Permesso di Soggiorno e Cittadinanza",
    p8Desc: "Assistenza per rinnovo del permesso di soggiorno, ricongiungimento familiare e pratiche per la cittadinanza italiana.",
    p9Title: "Pensioni Estere e Totalizzazione",
    p9Desc: "Gestione delle pensioni provenienti dall'estero, accordi bilaterali e totalizzazione dei contributi versati in più paesi.",
    p10Title: "Reddito di Inclusione e Sussidi",
    p10Desc: "Domanda per misure di inclusione attiva, sussidi sociali e prestazioni assistenziali per famiglie in difficoltà economica.",
    testimLabel: "Testimonianze",
    testimTitle: "Cosa Dicono i Nostri Clienti",
    t1: '"Studio professionale, competente e sempre disponibile. Ci hanno aiutato ad ottimizzare la fiscalità della nostra azienda in modo eccellente."',
    t2: '"Grazie allo Studio MMJB ho potuto aprire la mia attività in Italia senza stress. Servizio impeccabile e multilingue, consigliato!"',
    t3: '"Finalmente uno studio che ci segue a 360° — dalla contabilità al contenzioso. Professionali e umani allo stesso tempo."',
    contactLabel: "Contattaci",
    contactTitle: "Parliamo del Vostro Progetto",
    contactDesc: "Siamo a vostra disposizione per qualsiasi esigenza. Contattateci per una consulenza gratuita e senza impegno.",
    hours: "Lun–Ven: 9:00–18:00",
    formName: "Nome e Cognome",
    formNamePh: "Mario Rossi",
    formEmail: "Email",
    formEmailPh: "mario@esempio.it",
    formSubject: "Oggetto",
    formSubjectPh: "Come possiamo aiutarvi?",
    formService: "Servizio di Interesse",
    sOpt0: "-- Seleziona --",
    sOpt1: "Consulenza Fiscale",
    sOpt2: "Contabilità",
    sOpt3: "Gestione Paghe",
    sOpt4: "Costituzione Società",
    sOpt5: "Altro",
    formMsg: "Messaggio",
    formMsgPh: "Descrivete la vostra situazione o esigenza...",
    formSend: "Invia Messaggio",
    formSuccess: "Messaggio inviato! Vi risponderemo entro 24 ore.",
    footerDesc: "Il vostro partner di fiducia per la consulenza fiscale, contabile e aziendale in Italia.",
    footerNav: "Navigazione",
    footerCopy: "© 2026 Studio MMJB. Tutti i diritti riservati.",
    footerReg: "P.IVA 12345678901 — Iscritto all'Albo dei Dottori Commercialisti di Milano",
    cafLabel: "Centro di Assistenza Fiscale",
    cafTitle: "Servizi CAF",
    cafDesc: "Come Centro di Assistenza Fiscale autorizzato, offriamo tutti i servizi fiscali e previdenziali per cittadini e famiglie.",
    caf1Title: "Dichiarazione 730 / Modello Redditi",
    caf1Desc: "Compilazione e invio del modello 730 e Modello Redditi per lavoratori dipendenti, pensionati e autonomi.",
    caf2Title: "ISEE e DSU",
    caf2Desc: "Calcolo e presentazione dell'ISEE (Indicatore della Situazione Economica Equivalente) e della Dichiarazione Sostitutiva Unica.",
    caf3Title: "Bonus Sociali (Energia, Gas, Acqua)",
    caf3Desc: "Assistenza nella richiesta dei bonus per le utenze domestiche: elettricità, gas naturale e acqua per le famiglie in difficoltà.",
    caf4Title: "Assegno Unico Universale",
    caf4Desc: "Domanda e gestione dell'Assegno Unico per i figli a carico: calcolo, presentazione e aggiornamento annuale.",
    caf5Title: "RED / ObIS per INPS",
    caf5Desc: "Compilazione delle dichiarazioni reddituali RED e ObIS per il mantenimento delle prestazioni INPS (pensioni, invalidità).",
    caf6Title: "Successioni",
    caf6Desc: "Assistenza nella presentazione della dichiarazione di successione e nelle pratiche ereditarie presso l'Agenzia delle Entrate.",
    caf7Title: "Contratti di Locazione / Cedolare Secca",
    caf7Desc: "Registrazione, proroga e risoluzione di contratti di locazione. Opzione per il regime della cedolare secca.",
    caf8Title: "Pratiche INPS e Pensioni",
    caf8Desc: "Supporto per richieste di pensione, invalidità civile, indennità di accompagnamento e altri benefici previdenziali INPS.",
    caf9Title: "IMU / Imposta di Bollo",
    caf9Desc: "Calcolo e assistenza nel versamento dell'IMU sugli immobili e nella gestione dell'imposta di bollo virtuale.",
    caf10Title: "Codice Fiscale e Documenti",
    caf10Desc: "Richiesta e attribuzione del codice fiscale, assistenza per documenti fiscali per cittadini stranieri residenti in Italia.",
    caf11Title: "Reddito di Cittadinanza / Supporto Formazione",
    caf11Desc: "Domanda e rinnovo per le misure di sostegno al reddito e all'inclusione sociale previste dalla normativa vigente.",
    caf12Title: "Detrazioni e Deduzioni Fiscali",
    caf12Desc: "Ottimizzazione delle detrazioni (spese mediche, ristrutturazioni, ecobonus) e delle deduzioni per ridurre l'imposta dovuta.",
  },

  fr: {
    logoSub: "Cabinet Comptable",
    navHome: "Accueil",
    navServices: "Services",
    navAbout: "À Propos",
    navTeam: "Équipe",
    navContact: "Contact",
    heroTagline: "Professionnalisme · Fiabilité · Excellence",
    heroTitle: "Votre Partenaire de Confiance en Conseil Fiscal et Comptable",
    heroDesc: "Avec plus de 20 ans d'expérience, nous offrons des solutions sur mesure pour les particuliers, les professionnels et les entreprises en Italie.",
    heroCta: "Contactez-nous",
    heroServices: "Nos Services",
    stat1: "Années d'Expérience",
    stat2: "Clients Satisfaits",
    stat3: "Professionnels",
    stat4: "Conformité Garantie",
    servicesLabel: "Ce Que Nous Faisons",
    servicesTitle: "Nos Services",
    servicesDesc: "Nous offrons une gamme complète de services comptables, fiscaux et de conseil pour soutenir la croissance de votre entreprise.",
    s1Title: "Conseil Fiscal",
    s1Desc: "Planification fiscale optimisée, déclarations d'impôts, TVA, taxes foncières et gestion de toutes les obligations fiscales.",
    s2Title: "Comptabilité d'Entreprise",
    s2Desc: "Tenue de comptabilité ordinaire et simplifiée, bilans annuels, écritures comptables et reporting de gestion.",
    s3Title: "Gestion de la Paie",
    s3Desc: "Établissement des fiches de paie, gestion des cotisations sociales, contrats de travail, embauches et résiliations.",
    s4Title: "Création de Société",
    s4Desc: "Ouverture d'entreprises individuelles, SARL, SA, et assistance complète dans les démarches de démarrage d'activité.",
    s5Title: "Conseil Stratégique",
    s5Desc: "Business plan, analyse financière, contrôle de gestion et support aux décisions stratégiques d'entreprise.",
    s6Title: "Contentieux Fiscal",
    s6Desc: "Assistance en cas de contrôles fiscaux, recours, médiations avec l'administration fiscale italienne.",
    serviceMore: "En savoir plus →",
    aboutLabel: "À Propos",
    aboutTitle: "Une Référence dans le Conseil Comptable et Fiscal en Italie",
    aboutP1: "Fondé en 2004 à Milan, le Cabinet MMJB est devenu l'un des cabinets comptables les plus réputés du Nord de l'Italie. Notre mission est de fournir des conseils de haute qualité, personnalisés et conformes aux dernières réglementations.",
    aboutP2: "Nous servons des clients dans toute l'Italie et à l'étranger, avec une attention particulière aux PME, aux startups et aux entrepreneurs étrangers souhaitant opérer sur le marché italien.",
    abl1: "Inscrits à l'Ordre des Experts-Comptables",
    abl2: "Mise à jour continue sur les réglementations fiscales",
    abl3: "Service multilingue (IT, FR, EN, AR)",
    abl4: "Logiciels de gestion de dernière génération",
    aboutCta: "Demander une Consultation",
    badgeTxt: "Années d'Expérience",
    teamLabel: "Notre Équipe",
    teamTitle: "L'Équipe",
    teamDesc: "Des professionnels qualifiés et passionnés au service de vos objectifs.",
    role1: "Expert Comptable — Membre de ANCOT",
    bio1: "Spécialiste en fiscalité italienne et internationale, comptabilité d'entreprise, services CAF et Patronato. Accompagne particuliers, familles et entreprises dans toutes leurs démarches administratives et fiscales en Italie.",
    badgeCAF: "CAF Agréé",
    badgePatronato: "Patronato",
    patronatoLabel: "Patronato",
    patronatoTitle: "Services de Patronato",
    patronatoDesc: "Nous offrons une assistance gratuite pour toutes les démarches de sécurité sociale, d'assurance et d'aide sociale auprès de l'INPS, l'INAIL et autres organismes publics.",
    p1Title: "Retraite de Vieillesse et Anticipée",
    p1Desc: "Demande et calcul de la retraite de vieillesse, anticipée et quota 100/103 auprès de l'INPS.",
    p2Title: "Invalidité Civile et Handicap",
    p2Desc: "Demande de reconnaissance d'invalidité civile, cécité, surdité et loi 104 pour personnes handicapées.",
    p3Title: "Allocation d'Accompagnement",
    p3Desc: "Demande d'allocation d'accompagnement pour personnes dépendantes nécessitant une assistance continue.",
    p4Title: "NASpI / Allocation Chômage",
    p4Desc: "Demande de NASpI (indemnité de chômage), DIS-COLL pour collaborateurs et gestion des prestations chômage.",
    p5Title: "Maternité et Congés Parentaux",
    p5Desc: "Demande d'indemnité de maternité, paternité, congé parental et permissions loi 104 pour salariés et indépendants.",
    p6Title: "Accidents du Travail (INAIL)",
    p6Desc: "Déclaration et assistance pour accidents du travail et maladies professionnelles, rente INAIL et réhabilitation.",
    p7Title: "Allocations Familiales",
    p7Desc: "Demande d'allocations familiales (ANF) pour foyers avec enfants à charge, salariés et retraités.",
    p8Title: "Permis de Séjour et Citoyenneté",
    p8Desc: "Assistance pour le renouvellement du permis de séjour, regroupement familial et démarches de citoyenneté italienne.",
    p9Title: "Pensions Étrangères et Totalisation",
    p9Desc: "Gestion des pensions provenant de l'étranger, accords bilatéraux et totalisation des cotisations versées dans plusieurs pays.",
    p10Title: "Revenu d'Inclusion et Aides Sociales",
    p10Desc: "Demande de mesures d'inclusion active, aides sociales et prestations assistancielles pour familles en difficulté.",
    testimLabel: "Témoignages",
    testimTitle: "Ce que Disent nos Clients",
    t1: '"Cabinet professionnel, compétent et toujours disponible. Ils nous ont aidés à optimiser la fiscalité de notre entreprise de manière excellente."',
    t2: '"Grâce au Cabinet Rossi, j\'ai pu ouvrir mon activité en Italie sans stress. Service irréprochable et multilingue, je recommande !"',
    t3: '"Enfin un cabinet qui nous accompagne à 360° — de la comptabilité au contentieux. Professionnels et humains à la fois."',
    contactLabel: "Contactez-nous",
    contactTitle: "Parlons de Votre Projet",
    contactDesc: "Nous sommes à votre disposition pour tout besoin. Contactez-nous pour une consultation gratuite et sans engagement.",
    hours: "Lun–Ven : 9h00–18h00",
    formName: "Nom et Prénom",
    formNamePh: "Jean Dupont",
    formEmail: "Email",
    formEmailPh: "jean@exemple.fr",
    formSubject: "Objet",
    formSubjectPh: "Comment pouvons-nous vous aider ?",
    formService: "Service souhaité",
    sOpt0: "-- Sélectionner --",
    sOpt1: "Conseil Fiscal",
    sOpt2: "Comptabilité",
    sOpt3: "Gestion de la Paie",
    sOpt4: "Création de Société",
    sOpt5: "Autre",
    formMsg: "Message",
    formMsgPh: "Décrivez votre situation ou besoin...",
    formSend: "Envoyer le Message",
    formSuccess: "Message envoyé ! Nous vous répondrons dans les 24 heures.",
    footerDesc: "Votre partenaire de confiance pour le conseil fiscal, comptable et d'entreprise en Italie.",
    footerNav: "Navigation",
    footerCopy: "© 2026 Studio MMJB. Tous droits réservés.",
    footerReg: "N° TVA IT 12345678901 — Inscrit à l'Ordre des Experts-Comptables de Milan",
    cafLabel: "Centre d'Assistance Fiscale",
    cafTitle: "Services CAF",
    cafDesc: "En tant que Centre d'Assistance Fiscale agréé, nous offrons tous les services fiscaux et sociaux pour les particuliers et les familles.",
    caf1Title: "Déclaration 730 / Modèle Revenus",
    caf1Desc: "Remplissage et envoi du formulaire 730 et Modèle Revenus pour les salariés, retraités et indépendants.",
    caf2Title: "ISEE et DSU",
    caf2Desc: "Calcul et présentation de l'ISEE (Indicateur de Situation Économique Équivalente) et de la Déclaration Substitutive Unique.",
    caf3Title: "Bonus Sociaux (Énergie, Gaz, Eau)",
    caf3Desc: "Assistance pour la demande de bonus sur les services publics : électricité, gaz naturel et eau pour les familles en difficulté.",
    caf4Title: "Allocation Unique Universelle",
    caf4Desc: "Demande et gestion de l'Allocation Unique pour enfants à charge : calcul, soumission et mise à jour annuelle.",
    caf5Title: "RED / ObIS pour INPS",
    caf5Desc: "Remplissage des déclarations de revenus RED et ObIS pour le maintien des prestations INPS (retraites, invalidité).",
    caf6Title: "Successions",
    caf6Desc: "Assistance dans la présentation de la déclaration de succession et des démarches héréditaires auprès de l'Agence des Revenus.",
    caf7Title: "Contrats de Location / Impôt Forfaitaire",
    caf7Desc: "Enregistrement, prorogation et résiliation de contrats de location. Option pour le régime d'imposition forfaitaire (cedolare secca).",
    caf8Title: "Dossiers INPS et Retraites",
    caf8Desc: "Support pour les demandes de retraite, d'invalidité civile, d'allocation d'accompagnement et autres prestations INPS.",
    caf9Title: "IMU / Taxe de Timbre",
    caf9Desc: "Calcul et assistance dans le versement de l'IMU sur les biens immobiliers et la gestion de la taxe de timbre virtuelle.",
    caf10Title: "Code Fiscal et Documents",
    caf10Desc: "Demande et attribution du code fiscal, assistance pour les documents fiscaux pour les citoyens étrangers résidant en Italie.",
    caf11Title: "Revenu de Citoyenneté / Soutien à la Formation",
    caf11Desc: "Demande et renouvellement des mesures de soutien au revenu et à l'inclusion sociale prévues par la législation en vigueur.",
    caf12Title: "Déductions et Réductions Fiscales",
    caf12Desc: "Optimisation des déductions (frais médicaux, rénovations, ecobonus) pour réduire l'impôt dû.",
  },

  en: {
    logoSub: "Accounting Firm",
    navHome: "Home",
    navServices: "Services",
    navAbout: "About Us",
    navTeam: "Team",
    navContact: "Contact",
    heroTagline: "Professionalism · Reliability · Excellence",
    heroTitle: "Your Trusted Partner for Tax and Accounting Advisory in Italy",
    heroDesc: "With over 20 years of experience, we offer tailored solutions for individuals, professionals and businesses across Italy.",
    heroCta: "Contact Us Now",
    heroServices: "Our Services",
    stat1: "Years of Experience",
    stat2: "Satisfied Clients",
    stat3: "Professionals",
    stat4: "Guaranteed Compliance",
    servicesLabel: "What We Do",
    servicesTitle: "Our Services",
    servicesDesc: "We offer a comprehensive range of accounting, tax and advisory services to support the growth of your business.",
    s1Title: "Tax Advisory",
    s1Desc: "Optimized tax planning, income tax returns, VAT, property taxes and management of all tax obligations.",
    s2Title: "Business Accounting",
    s2Desc: "Ordinary and simplified bookkeeping, annual financial statements, accounting entries and management reporting.",
    s3Title: "Payroll Management",
    s3Desc: "Payslip processing, social security management, employment contracts, hirings and terminations.",
    s4Title: "Company Formation",
    s4Desc: "Setting up sole proprietorships, SRLs, SPAs, and complete assistance in business start-up procedures.",
    s5Title: "Strategic Consulting",
    s5Desc: "Business planning, financial analysis, management control and support for strategic business decisions.",
    s6Title: "Tax Litigation",
    s6Desc: "Assistance in tax audits, tax appeals, and mediations with the Italian Revenue Agency.",
    serviceMore: "Learn more →",
    aboutLabel: "About Us",
    aboutTitle: "A Reference in Business and Tax Advisory in Italy",
    aboutP1: "Founded in 2004 in Milan, MMJB has grown to become one of the most respected accounting firms in Northern Italy. Our mission is to provide high-quality, personalized advice updated to the latest regulations.",
    aboutP2: "We serve clients across Italy and abroad, with a particular focus on SMEs, startups and foreign entrepreneurs wishing to operate in the Italian market.",
    abl1: "Registered with the Order of Chartered Accountants",
    abl2: "Continuous updates on tax regulations",
    abl3: "Multilingual service (IT, FR, EN, AR)",
    abl4: "Latest generation management software",
    aboutCta: "Request a Consultation",
    badgeTxt: "Years of Experience",
    teamLabel: "Our People",
    teamTitle: "Our Team",
    teamDesc: "Qualified and passionate professionals serving your goals.",
    role1: "Chartered Accountant — Member of ANCOT",
    bio1: "Specialist in Italian and international taxation, business accounting, CAF and Patronato services. Assists individuals, families and businesses with all administrative and tax procedures in Italy.",
    badgeCAF: "Authorized CAF",
    badgePatronato: "Patronato",
    patronatoLabel: "Patronato",
    patronatoTitle: "Patronato Services",
    patronatoDesc: "We offer free assistance for all social security, insurance and welfare procedures with INPS, INAIL and other public bodies.",
    p1Title: "Old Age and Early Retirement",
    p1Desc: "Application and calculation of old age pension, early retirement and quota 100/103 with INPS.",
    p2Title: "Civil Disability and Handicap",
    p2Desc: "Application for recognition of civil disability, blindness, deafness and law 104 for people with disabilities.",
    p3Title: "Attendance Allowance",
    p3Desc: "Application for attendance allowance for non-self-sufficient persons requiring continuous care.",
    p4Title: "NASpI / Unemployment Benefit",
    p4Desc: "Application for NASpI (unemployment benefit), DIS-COLL for collaborators and management of unemployment benefits.",
    p5Title: "Maternity and Parental Leave",
    p5Desc: "Application for maternity, paternity, parental leave allowance and law 104 permits for employees and self-employed.",
    p6Title: "Work Accidents (INAIL)",
    p6Desc: "Reporting and assistance for work accidents and occupational diseases, INAIL annuity and rehabilitation.",
    p7Title: "Family Allowances",
    p7Desc: "Application for family allowances (ANF) for households with dependent children, employees and retirees.",
    p8Title: "Residence Permit and Citizenship",
    p8Desc: "Assistance for renewal of residence permit, family reunification and Italian citizenship procedures.",
    p9Title: "Foreign Pensions and Totalization",
    p9Desc: "Management of pensions from abroad, bilateral agreements and totalization of contributions paid in multiple countries.",
    p10Title: "Inclusion Income and Social Benefits",
    p10Desc: "Application for active inclusion measures, social subsidies and welfare benefits for families in economic difficulty.",
    testimLabel: "Testimonials",
    testimTitle: "What Our Clients Say",
    t1: '"Professional, competent and always available. They helped us optimize our company\'s tax position in an excellent manner."',
    t2: '"Thanks to Studio MMJB, I was able to open my business in Italy stress-free. Impeccable multilingual service, highly recommended!"',
    t3: '"Finally a firm that supports us 360° — from accounting to litigation. Professional and human at the same time."',
    contactLabel: "Contact Us",
    contactTitle: "Let's Talk About Your Project",
    contactDesc: "We are at your disposal for any need. Contact us for a free, no-obligation consultation.",
    hours: "Mon–Fri: 9:00 AM–6:00 PM",
    formName: "Full Name",
    formNamePh: "John Smith",
    formEmail: "Email",
    formEmailPh: "john@example.com",
    formSubject: "Subject",
    formSubjectPh: "How can we help you?",
    formService: "Service of Interest",
    sOpt0: "-- Select --",
    sOpt1: "Tax Advisory",
    sOpt2: "Accounting",
    sOpt3: "Payroll Management",
    sOpt4: "Company Formation",
    sOpt5: "Other",
    formMsg: "Message",
    formMsgPh: "Describe your situation or need...",
    formSend: "Send Message",
    formSuccess: "Message sent! We will reply within 24 hours.",
    footerDesc: "Your trusted partner for tax, accounting and business advisory in Italy.",
    footerNav: "Navigation",
    footerCopy: "© 2026 Studio MMJB. All rights reserved.",
    footerReg: "VAT IT 12345678901 — Registered with the Order of Chartered Accountants of Milan",
    cafLabel: "Fiscal Assistance Centre",
    cafTitle: "CAF Services",
    cafDesc: "As an authorized Fiscal Assistance Centre (CAF), we offer all tax and social security services for individuals and families.",
    caf1Title: "730 Tax Return / Income Model",
    caf1Desc: "Completion and submission of the 730 form and Income Model for employees, retirees and self-employed workers.",
    caf2Title: "ISEE and DSU",
    caf2Desc: "Calculation and submission of the ISEE (Equivalent Economic Situation Indicator) and Substitute Unique Declaration.",
    caf3Title: "Social Bonuses (Energy, Gas, Water)",
    caf3Desc: "Assistance in applying for household utility bonuses: electricity, natural gas and water for families in need.",
    caf4Title: "Universal Child Allowance",
    caf4Desc: "Application and management of the Universal Child Allowance: calculation, submission and annual update.",
    caf5Title: "RED / ObIS for INPS",
    caf5Desc: "Completion of RED and ObIS income declarations for maintaining INPS benefits (pensions, disability).",
    caf6Title: "Inheritances",
    caf6Desc: "Assistance in filing inheritance declarations and estate procedures with the Revenue Agency.",
    caf7Title: "Rental Contracts / Flat-Rate Tax",
    caf7Desc: "Registration, extension and termination of rental contracts. Option for the flat-rate tax scheme (cedolare secca).",
    caf8Title: "INPS and Pension Applications",
    caf8Desc: "Support for pension requests, civil disability, attendance allowance and other INPS social security benefits.",
    caf9Title: "IMU / Stamp Duty",
    caf9Desc: "Calculation and assistance in IMU payment on properties and management of virtual stamp duty.",
    caf10Title: "Tax Code and Documents",
    caf10Desc: "Request and assignment of tax code, assistance with tax documents for foreign citizens residing in Italy.",
    caf11Title: "Citizenship Income / Training Support",
    caf11Desc: "Application and renewal for income support and social inclusion measures provided by current legislation.",
    caf12Title: "Tax Deductions and Allowances",
    caf12Desc: "Optimization of deductions (medical expenses, renovations, ecobonus) and allowances to reduce tax liability.",
  },

  ar: {
    logoSub: "مكتب محاسبة قانونية",
    navHome: "الرئيسية",
    navServices: "الخدمات",
    navAbout: "من نحن",
    navTeam: "الفريق",
    navContact: "اتصل بنا",
    heroTagline: "الاحترافية · الموثوقية · التميز",
    heroTitle: "شريككم الموثوق للاستشارات الضريبية والمحاسبية في إيطاليا",
    heroDesc: "مع أكثر من 20 عامًا من الخبرة، نقدم حلولاً مخصصة للأفراد والمهنيين والشركات في جميع أنحاء إيطاليا.",
    heroCta: "تواصل معنا الآن",
    heroServices: "خدماتنا",
    stat1: "سنوات من الخبرة",
    stat2: "عميل راضٍ",
    stat3: "متخصص",
    stat4: "امتثال مضمون",
    servicesLabel: "ما نقدمه",
    servicesTitle: "خدماتنا",
    servicesDesc: "نقدم مجموعة شاملة من الخدمات المحاسبية والضريبية والاستشارية لدعم نمو أعمالكم.",
    s1Title: "الاستشارات الضريبية",
    s1Desc: "التخطيط الضريبي الأمثل، إقرارات الدخل، ضريبة القيمة المضافة، الضرائب العقارية وإدارة جميع الالتزامات الضريبية.",
    s2Title: "محاسبة الشركات",
    s2Desc: "ضبط الحسابات العادية والمبسطة، القوائم المالية السنوية، القيود المحاسبية والتقارير الإدارية.",
    s3Title: "إدارة الرواتب",
    s3Desc: "إعداد كشوف الرواتب، إدارة الضمان الاجتماعي، عقود العمل، التوظيف والإنهاء.",
    s4Title: "تأسيس الشركات",
    s4Desc: "تأسيس المؤسسات الفردية والشركات ذات المسؤولية المحدودة والمساهمة، والمساعدة الكاملة في إجراءات بدء النشاط.",
    s5Title: "الاستشارات الاستراتيجية",
    s5Desc: "خطط الأعمال، التحليل المالي، مراقبة الإدارة والدعم في القرارات الاستراتيجية.",
    s6Title: "النزاعات الضريبية",
    s6Desc: "المساعدة في حالات الفحص الضريبي، الطعون الضريبية والوساطة مع هيئة الإيرادات الإيطالية.",
    serviceMore: "اكتشف المزيد ←",
    aboutLabel: "من نحن",
    aboutTitle: "مرجع في الاستشارات التجارية والمحاسبية في إيطاليا",
    aboutP1: "تأسس مكتب روسي وشركاه عام 2004 في ميلانو، ونما ليصبح أحد أبرز مكاتب المحاسبة في شمال إيطاليا. مهمتنا تقديم استشارات عالية الجودة، مخصصة ومحدّثة وفق أحدث التشريعات.",
    aboutP2: "نخدم عملاء في جميع أنحاء إيطاليا والخارج، مع اهتمام خاص بالمؤسسات الصغيرة والمتوسطة والشركات الناشئة ورجال الأعمال الأجانب الراغبين في العمل في السوق الإيطالي.",
    abl1: "مسجلون في نقابة المحاسبين القانونيين",
    abl2: "تحديث مستمر على اللوائح الضريبية",
    abl3: "خدمة متعددة اللغات (IT, FR, EN, AR)",
    abl4: "أحدث برامج الإدارة المالية",
    aboutCta: "طلب استشارة",
    badgeTxt: "سنوات من الخبرة",
    teamLabel: "فريقنا",
    teamTitle: "فريق العمل",
    teamDesc: "متخصصون مؤهلون وشغوفون في خدمة أهدافكم.",
    role1: "خبير محاسب — عضو في ANCOT",
    bio1: "متخصص في الضرائب الإيطالية والدولية، ومحاسبة الشركات، وخدمات CAF والـ Patronato. يُرافق الأفراد والعائلات والشركات في جميع إجراءاتهم الإدارية والضريبية في إيطاليا.",
    badgeCAF: "CAF معتمد",
    badgePatronato: "باترونطو",
    patronatoLabel: "باترونطو",
    patronatoTitle: "خدمات الباترونطو",
    patronatoDesc: "نقدم مساعدة مجانية لجميع الإجراءات المتعلقة بالضمان الاجتماعي والتأمين والرعاية الاجتماعية لدى INPS وINAIL وغيرها من الهيئات العامة.",
    p1Title: "معاش الشيخوخة والتقاعد المبكر",
    p1Desc: "طلب وحساب معاش الشيخوخة والتقاعد المبكر وكوتا 100/103 لدى INPS.",
    p2Title: "الإعاقة المدنية والعجز",
    p2Desc: "طلب الاعتراف بالإعاقة المدنية والعمى والصمم والقانون 104 للأشخاص ذوي الإعاقة.",
    p3Title: "بدل المرافقة",
    p3Desc: "طلب بدل المرافقة للأشخاص غير القادرين على الاعتناء بأنفسهم الذين يحتاجون إلى رعاية مستمرة.",
    p4Title: "NASpI / إعانة البطالة",
    p4Desc: "طلب NASpI (إعانة البطالة) وDIS-COLL للمتعاونين وإدارة استحقاقات البطالة.",
    p5Title: "الأمومة وإجازات الوالدين",
    p5Desc: "طلب إعانة الأمومة والأبوة وإجازة الوالدين وتصاريح القانون 104 للعمال والمستقلين.",
    p6Title: "حوادث العمل (INAIL)",
    p6Desc: "الإبلاغ والمساعدة في حوادث العمل والأمراض المهنية وريع INAIL وإعادة التأهيل.",
    p7Title: "المخصصات العائلية",
    p7Desc: "طلب المخصصات العائلية (ANF) للأسر ذات المعالين من الموظفين والمتقاعدين.",
    p8Title: "تصريح الإقامة والجنسية",
    p8Desc: "المساعدة في تجديد تصريح الإقامة ولمّ شمل الأسرة وإجراءات الجنسية الإيطالية.",
    p9Title: "المعاشات الأجنبية والتجميع",
    p9Desc: "إدارة المعاشات القادمة من الخارج والاتفاقيات الثنائية وتجميع المساهمات المدفوعة في عدة دول.",
    p10Title: "دخل الإدماج والمساعدات الاجتماعية",
    p10Desc: "طلب تدابير الإدماج الفعّال والإعانات الاجتماعية والمزايا المساعدة للعائلات في صعوبة اقتصادية.",
    testimLabel: "شهادات العملاء",
    testimTitle: "ماذا يقول عملاؤنا",
    t1: '"مكتب احترافي وكفؤ ودائم الحضور. ساعدونا في تحسين الوضع الضريبي لشركتنا بشكل ممتاز."',
    t2: '"بفضل مكتب روسي، تمكنت من فتح نشاطي في إيطاليا دون ضغوط. خدمة متميزة ومتعددة اللغات، أنصح به بشدة!"',
    t3: '"أخيرًا مكتب يرافقنا بشكل متكامل — من المحاسبة إلى النزاعات. محترفون وإنسانيون في آنٍ واحد."',
    contactLabel: "تواصل معنا",
    contactTitle: "لنتحدث عن مشروعكم",
    contactDesc: "نحن في خدمتكم لأي احتياج. تواصلوا معنا للحصول على استشارة مجانية وبدون التزام.",
    hours: "الاثنين–الجمعة: 9:00–18:00",
    formName: "الاسم الكامل",
    formNamePh: "محمد علي",
    formEmail: "البريد الإلكتروني",
    formEmailPh: "mohammed@example.com",
    formSubject: "الموضوع",
    formSubjectPh: "كيف يمكننا مساعدتكم؟",
    formService: "الخدمة المطلوبة",
    sOpt0: "-- اختر --",
    sOpt1: "الاستشارات الضريبية",
    sOpt2: "المحاسبة",
    sOpt3: "إدارة الرواتب",
    sOpt4: "تأسيس الشركات",
    sOpt5: "أخرى",
    formMsg: "الرسالة",
    formMsgPh: "اشرح وضعكم أو احتياجاتكم...",
    formSend: "إرسال الرسالة",
    formSuccess: "تم إرسال رسالتكم! سنرد عليكم خلال 24 ساعة.",
    footerDesc: "شريككم الموثوق للاستشارات الضريبية والمحاسبية والتجارية في إيطاليا.",
    footerNav: "التنقل",
    footerCopy: "© 2026 Studio MMJB. جميع الحقوق محفوظة.",
    footerReg: "رقم الضريبة IT 12345678901 — مسجل في نقابة المحاسبين القانونيين في ميلانو",
    cafLabel: "مركز المساعدة الضريبية",
    cafTitle: "خدمات CAF",
    cafDesc: "بوصفنا مركزًا معتمدًا للمساعدة الضريبية (CAF)، نقدم جميع الخدمات الضريبية والاجتماعية للأفراد والعائلات.",
    caf1Title: "إقرار الدخل 730 / نموذج الدخل",
    caf1Desc: "تعبئة وإرسال نموذج 730 ونموذج الدخل للعمال والمتقاعدين وأصحاب المهن الحرة.",
    caf2Title: "ISEE و DSU",
    caf2Desc: "حساب وتقديم مؤشر الوضع الاقتصادي المعادل (ISEE) والإقرار البديل الموحد (DSU).",
    caf3Title: "المنح الاجتماعية (الكهرباء، الغاز، الماء)",
    caf3Desc: "المساعدة في طلب منح المرافق المنزلية: الكهرباء والغاز الطبيعي والماء للعائلات المحتاجة.",
    caf4Title: "المخصص الموحد الشامل للأطفال",
    caf4Desc: "تقديم وإدارة طلب المخصص الموحد للأطفال المعالين: الحساب والتقديم والتحديث السنوي.",
    caf5Title: "RED / ObIS لـ INPS",
    caf5Desc: "تعبئة إقرارات الدخل RED وObIS للحفاظ على استحقاقات INPS (المعاشات التقاعدية، الإعاقة).",
    caf6Title: "الميراث والتركات",
    caf6Desc: "المساعدة في تقديم إقرار الميراث وإجراءات التركة لدى دائرة الإيرادات الإيطالية.",
    caf7Title: "عقود الإيجار / الضريبة الاستثنائية",
    caf7Desc: "تسجيل وتمديد وإنهاء عقود الإيجار. الاختيار لنظام الضريبة الاستثنائية الثابتة.",
    caf8Title: "ملفات INPS والمعاشات التقاعدية",
    caf8Desc: "دعم لطلبات التقاعد والعجز المدني وبدل المرافقة وسائر استحقاقات INPS.",
    caf9Title: "IMU / ضريبة الطوابع",
    caf9Desc: "حساب والمساعدة في دفع ضريبة IMU على العقارات وإدارة ضريبة الطوابع الإلكترونية.",
    caf10Title: "الرقم الضريبي والوثائق",
    caf10Desc: "طلب وتخصيص الرقم الضريبي، والمساعدة في الوثائق الضريبية للمواطنين الأجانب المقيمين في إيطاليا.",
    caf11Title: "دخل المواطنة / دعم التكوين المهني",
    caf11Desc: "تقديم وتجديد طلبات دعم الدخل والإدماج الاجتماعي وفق التشريعات السارية.",
    caf12Title: "التخفيضات والاستقطاعات الضريبية",
    caf12Desc: "تحسين الخصومات (المصاريف الطبية، التجديدات، ecobonus) والاستقطاعات لتقليل الضريبة المستحقة.",
  }
};

// ===== LANGUAGE SWITCHER =====
let currentLang = 'it';

function applyLanguage(lang) {
  currentLang = lang;
  const t = translations[lang];
  const isRTL = lang === 'ar';

  // Set dir and lang attributes
  document.documentElement.setAttribute('lang', lang);
  document.documentElement.setAttribute('dir', isRTL ? 'rtl' : 'ltr');
  document.body.setAttribute('dir', isRTL ? 'rtl' : 'ltr');

  // Update font for Arabic
  if (isRTL) {
    document.body.style.fontFamily = "'Amiri', 'Inter', sans-serif";
  } else {
    document.body.style.fontFamily = "'Inter', sans-serif";
  }

  // Translate all data-i18n elements
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) el.textContent = t[key];
  });

  // Translate placeholder attributes
  document.querySelectorAll('[data-placeholder-i18n]').forEach(el => {
    const key = el.getAttribute('data-placeholder-i18n');
    if (t[key] !== undefined) el.setAttribute('placeholder', t[key]);
  });

  // Update active button
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
  });
}

// ===== NAVBAR SCROLL =====
const navbar = document.getElementById('navbar');
window.addEventListener('scroll', () => {
  navbar.classList.toggle('scrolled', window.scrollY > 60);
});

// ===== HAMBURGER =====
const hamburger = document.getElementById('hamburger');
const navLinks = document.getElementById('navLinks');
hamburger.addEventListener('click', () => {
  navLinks.classList.toggle('open');
});
navLinks.querySelectorAll('a').forEach(a => {
  a.addEventListener('click', () => navLinks.classList.remove('open'));
});

// ===== BACK TO TOP =====
const backToTop = document.getElementById('backToTop');
window.addEventListener('scroll', () => {
  backToTop.classList.toggle('show', window.scrollY > 400);
});

// ===== CONTACT FORM =====
const contactForm = document.getElementById('contactForm');
const formSuccess = document.getElementById('formSuccess');
contactForm.addEventListener('submit', e => {
  e.preventDefault();
  formSuccess.classList.add('show');
  contactForm.reset();
  setTimeout(() => formSuccess.classList.remove('show'), 5000);
});

// ===== SMOOTH SCROLL OFFSET for fixed nav =====
document.querySelectorAll('a[href^="#"]').forEach(a => {
  a.addEventListener('click', e => {
    const target = document.querySelector(a.getAttribute('href'));
    if (target) {
      e.preventDefault();
      const offset = 80;
      window.scrollTo({ top: target.offsetTop - offset, behavior: 'smooth' });
    }
  });
});

// ===== INTERSECTION OBSERVER (fade-in) =====
const observer = new IntersectionObserver((entries) => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      entry.target.style.opacity = '1';
      entry.target.style.transform = 'translateY(0)';
      observer.unobserve(entry.target);
    }
  });
}, { threshold: 0.1 });

document.querySelectorAll('.service-card, .team-card, .testimon-card, .stat-item').forEach(el => {
  el.style.opacity = '0';
  el.style.transform = 'translateY(30px)';
  el.style.transition = 'opacity 0.6s ease, transform 0.6s ease';
  observer.observe(el);
});

// ===== INIT LANG BUTTONS =====
document.querySelectorAll('.lang-btn').forEach(btn => {
  btn.addEventListener('click', () => applyLanguage(btn.getAttribute('data-lang')));
});

// Init with Italian
applyLanguage('it');
